const assert = require('node:assert/strict');
async function checkNotes(page) {
  await page.evaluate(() => {
    const records = { global: {}, workspace: {} };
    const original = window.sentMessages.push.bind(window.sentMessages);
    window.sentMessages.push = function (message) {
      original(message);
      const emit = data => setTimeout(() => window.dispatchEvent(new MessageEvent('message', { data })), 0);
      if (message.type === 'notes.list') emit({ type: 'notes.list.result', scope: message.scope, notes: Object.values(records[message.scope]) });
      if (message.type === 'notes.save') {
        if (window.noteReject) { window.noteReject = false; emit({ type: 'notes.save.result', scope: message.scope, id: message.note.id, error: 'Conflict' }); return; }
        const note = { ...message.note, revision: message.note.revision + 1, updatedAt: new Date().toISOString() };
        records[message.scope][note.id] = note;
        emit({ type: 'notes.save.result', scope: message.scope, id: note.id, note });
      }
    };
    window.noteRecords = records;
  });
  const bounds = () => page.locator('#timeline').evaluate(el => ({ width: el.clientWidth, left: el.getBoundingClientRect().left }));
  const before = await bounds();
  await page.locator('#notes-toggle').click();
  assert.equal(await page.locator('.notes-header-actions #notes-new').isVisible(), true);
  const newButton = await page.locator('#notes-new').boundingBox();
  const closeButton = await page.locator('#notes-close').boundingBox();
  assert.ok(newButton.x + newButton.width <= closeButton.x);
  assert.equal(newButton.y, closeButton.y);
  assert.deepEqual(await bounds(), before);
  await page.locator('#notes-resize').focus();
  await page.keyboard.press('ArrowLeft');
  assert.ok((await page.locator('#notes-panel').boundingBox()).width > 280);
  const handle = await page.locator('#notes-resize').boundingBox();
  await page.mouse.move(handle.x + handle.width / 2, handle.y + 40);
  await page.mouse.down();
  await page.mouse.move(0, handle.y + 40, { steps: 10 });
  await page.mouse.up();
  const expanded = await page.locator('#notes-panel').boundingBox();
  const available = await page.locator('#notes-panel').evaluate(el => el.parentElement.clientWidth);
  assert.ok(expanded.width > available * .8);
  assert.ok(expanded.x >= 0 && expanded.x + expanded.width <= page.viewportSize().width);
  await page.locator('#notes-resize').focus();
  await page.keyboard.press('ArrowRight');
  assert.ok((await page.locator('#notes-panel').boundingBox()).width < expanded.width);
  assert.deepEqual(await bounds(), before);
  await page.locator('#notes-new').click();
  await page.locator('#notes-title').fill('Reusable prompt');
  await page.locator('#notes-body').fill('My note\n두 번째 줄');
  await page.waitForFunction(() => document.querySelector('#notes-status').textContent === 'Saved');
  await page.locator('#notes-back').click();
  await page.locator('#notes-list button').click();
  assert.equal(await page.locator('#notes-body').inputValue(), 'My note\n두 번째 줄');
  await page.locator('#prompt').fill('Existing draft');
  await page.locator('#notes-insert').click();
  assert.equal(await page.locator('#prompt').inputValue(), 'Existing draft\n\nMy note\n두 번째 줄');
  assert.deepEqual(await bounds(), before);
  assert.equal(await page.locator('#notes-panel').isVisible(), false);
  await page.locator('#notes-toggle').click();
  await page.locator('#notes-back').click();
  await page.getByRole('tab', { name: 'Workspace', exact: true }).click();
  assert.equal(await page.locator('#notes-tab-workspace').getAttribute('aria-selected'), 'true');
  await page.keyboard.press('ArrowLeft');
  assert.equal(await page.locator('#notes-tab-global').getAttribute('aria-selected'), 'true');
  await page.keyboard.press('End');
  assert.equal(await page.locator('#notes-tab-workspace').getAttribute('aria-selected'), 'true');
  await page.waitForFunction(() => document.querySelector('#notes-list').textContent === 'No notes yet.');
  await page.locator('#notes-new').click();
  await page.locator('#notes-body').fill('Workspace note');
  await page.waitForFunction(() => document.querySelector('#notes-status').textContent === 'Saved');
  assert.equal(await page.evaluate(() => Object.values(window.noteRecords.global)[0].body), 'My note\n두 번째 줄');
  await page.evaluate(() => { window.noteReject = true; });
  await page.locator('#notes-body').fill('Preserve conflicting edits');
  await page.waitForFunction(() => !document.querySelector('#notes-save-copy').hidden);
  assert.equal(await page.locator('#notes-new').isDisabled(), true);
  assert.equal(await page.locator('#notes-body').inputValue(), 'Preserve conflicting edits');
  await page.locator('#notes-save-copy').click();
  await page.waitForFunction(() => document.querySelector('#notes-status').textContent === 'Saved');
  assert.equal(await page.evaluate(() => Object.values(window.noteRecords.workspace).length), 2);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#notes-panel').isVisible(), false);
  await page.screenshot({ path: '/tmp/af-notes-closed.png' });
  await page.locator('#notes-toggle').click();
  await page.screenshot({ path: '/tmp/af-notes-open.png' });
  await page.locator('#notes-close').click();
  await page.setViewportSize({ width: 360, height: 720 });
  const narrow = await bounds();
  await page.locator('#notes-toggle').click();
  const panel = await page.locator('#notes-panel').boundingBox();
  assert.ok(panel.x >= 0 && panel.x + panel.width <= 360);
  await page.locator('#notes-close').click();
  assert.deepEqual(await bounds(), narrow);
  assert.equal(await page.evaluate(() => window.sentMessages.some(m => m.type === 'chat.send' || m.type === 'run.cancel')), false);
  console.log('Notes: autosave, scopes, reopen, draft insertion, Escape and unchanged chat width passed.');
}
module.exports = { checkNotes };
