"use strict";

const { execFile: execFileCallback } = require("node:child_process");
const { join } = require("node:path");
const { promisify } = require("node:util");

const execFile = promisify(execFileCallback);
const FIXTURE_ID = "kanban-manager-transition-fixture";

async function runManager(managerPath, args) {
  try {
    await execFile("python3", [managerPath, ...args], {
      encoding: "utf8",
      maxBuffer: 4 * 1024 * 1024,
      shell: false,
      windowsHide: true,
    });
  } catch (error) {
    const detail = String(error.stderr || error.stdout || error.message || "");
    throw new Error(`fixture manager command failed: ${args[0]}: ${detail}`);
  }
}

async function createReadyKanbanFixture({ managerPath, projectRoot }) {
  const packagePath = join(
    projectRoot,
    ".agent-factory",
    "work-units",
    FIXTURE_ID,
  );
  const manager = (...args) => runManager(managerPath, args);

  await manager(
    "create",
    packagePath,
    "--id",
    FIXTURE_ID,
    "--title",
    "Kanban Manager Transition Fixture",
    "--project-id",
    "agent-factory-workspace",
    "--language",
    "ko",
    "--theme",
    "default",
  );
  await manager(
    "section-items-put",
    packagePath,
    "basis",
    "--string",
    "/0/id",
    "fixture-intake-basis",
    "--string",
    "/0/kind",
    "intake-basis-ref",
    "--string",
    "/0/content",
    "Kanban transition fixture basis",
    "--string",
    "/0/sourceRefs/0/artifactType",
    "intake",
    "--string",
    "/0/sourceRefs/0/id",
    "agent-factory-workspace-kanban-viewer",
    "--string",
    "/0/sourceRefs/0/path",
    ".agent-factory/intakes/agent-factory-workspace-kanban-viewer",
    "--string",
    "/0/sourceRefs/0/anchor/sectionId",
    "work-unit-basis",
    "--string",
    "/0/sourceRefs/0/anchor/itemId",
    "work-unit-basis-kanban-authoring",
  );
  await manager(
    "section-items-put",
    packagePath,
    "work-definition",
    "--string",
    "/0/id",
    "fixture-goal",
    "--string",
    "/0/kind",
    "goal",
    "--string",
    "/0/content",
    "Exercise a manager-owned ready to backlog transition.",
    "--string",
    "/1/id",
    "fixture-scope",
    "--string",
    "/1/kind",
    "scope",
    "--string-list",
    "/1/content",
    "Create an isolated canonical fixture.",
    "--string",
    "/2/id",
    "fixture-out-of-scope",
    "--string",
    "/2/kind",
    "out-of-scope",
    "--string-list",
    "/2/content",
    "Mutate repository Work Units.",
    "--string",
    "/3/id",
    "fixture-expected-output",
    "--string",
    "/3/kind",
    "expected-output",
    "--string-list",
    "/3/content",
    "A canonical fixture transition result.",
  );
  await manager(
    "section-items-put",
    packagePath,
    "plan",
    "--string",
    "/0/id",
    "fixture-plan",
    "--string",
    "/0/kind",
    "plan-step",
    "--string-list",
    "/0/content",
    "Transition ready to backlog with the installed manager.",
  );
  await manager(
    "section-items-put",
    packagePath,
    "execution-context",
    "--string",
    "/0/id",
    "fixture-execution-context",
    "--string",
    "/0/kind",
    "execution-context",
    "--string",
    "/0/content/goalId",
    FIXTURE_ID,
    "--string",
    "/0/content/objective",
    "Verify a canonical Kanban transition fixture.",
    "--string",
    "/0/content/execInvocation",
    `/goal ${FIXTURE_ID}`,
    "--string",
    "/0/content/executionAgent",
    "Test",
    "--string",
    "/0/content/repository",
    projectRoot,
    "--string",
    "/0/content/baseRef",
    "main",
    "--string",
    "/0/content/branch",
    `work-unit/${FIXTURE_ID}`,
    "--string",
    "/0/content/worktreePath",
    join(projectRoot, ".agent-factory", "worktree", FIXTURE_ID),
  );
  await manager(
    "section-items-put",
    packagePath,
    "acceptance-and-verification",
    "--string",
    "/0/id",
    "fixture-acceptance",
    "--string",
    "/0/kind",
    "acceptance-criterion",
    "--string-list",
    "/0/content",
    "The installed manager accepts ready to backlog.",
    "--string",
    "/1/id",
    "fixture-definition-of-done",
    "--string",
    "/1/kind",
    "definition-of-done",
    "--string-list",
    "/1/content",
    "The authoritative reader observes backlog.",
    "--string",
    "/2/id",
    "fixture-test-criterion",
    "--string",
    "/2/kind",
    "test-criterion",
    "--string-list",
    "/2/content",
    "No repository Work Unit supplies fixture lifecycle state.",
    "--string",
    "/3/id",
    "fixture-quality-check",
    "--string",
    "/3/kind",
    "quality-check",
    "--string",
    "/3/content",
    "Fixture verification pending.",
    "--string",
    "/3/attributes/status",
    "planned",
    "--empty-list",
    "/3/attributes/evidence",
  );
  await manager(
    "section-items-put",
    packagePath,
    "execution",
    "--string",
    "/0/id",
    "fixture-execution-result",
    "--string",
    "/0/kind",
    "execution-result",
    "--string",
    "/0/content",
    "Fixture execution pending.",
    "--string",
    "/0/attributes/status",
    "pending",
    "--string",
    "/0/attributes/verificationResult",
    "pending",
    "--empty-list",
    "/0/attributes/evidence",
  );
  await manager(
    "section-items-put",
    packagePath,
    "ai-review",
    "--string",
    "/0/id",
    "fixture-ai-checklist",
    "--string",
    "/0/kind",
    "ai-checklist",
    "--string-list",
    "/0/content",
    "Fixture remains isolated.",
    "--string",
    "/1/id",
    "fixture-ai-review-result",
    "--string",
    "/1/kind",
    "ai-review-result",
    "--string",
    "/1/content",
    "Fixture review pending.",
    "--string",
    "/1/attributes/result",
    "pending",
    "--string",
    "/1/attributes/checklistResult",
    "pending",
    "--empty-list",
    "/1/attributes/evidence",
  );
  await manager(
    "section-items-put",
    packagePath,
    "human-review",
    "--string",
    "/0/id",
    "fixture-human-review-result",
    "--string",
    "/0/kind",
    "human-review-result",
    "--string",
    "/0/content",
    "Fixture Human review pending.",
    "--string",
    "/0/attributes/status",
    "pending",
    "--string",
    "/1/id",
    "fixture-human-checklist",
    "--string",
    "/1/kind",
    "human-checklist",
    "--string-list",
    "/1/content",
    "Inspect the fixture transition.",
    "--string",
    "/2/id",
    "fixture-human-review-method",
    "--string",
    "/2/kind",
    "human-review-method",
    "--string",
    "/2/content",
    "Review the isolated fixture result.",
  );
  await manager(
    "section-items-put",
    packagePath,
    "report",
    "--string",
    "/0/id",
    "fixture-report-result",
    "--string",
    "/0/kind",
    "report-result",
    "--string",
    "/0/content",
    "Fixture report pending.",
    "--string",
    "/0/attributes/verificationResult",
    "pending",
    "--empty-list",
    "/0/attributes/evidence",
  );
  await manager(
    "metadata-set",
    packagePath,
    "readiness",
    "--boolean",
    "/contractValid",
    "true",
    "--boolean",
    "/intakeTraceabilityValid",
    "true",
    "--boolean",
    "/definitionComplete",
    "true",
    "--boolean",
    "/executionContextComplete",
    "true",
    "--boolean",
    "/verificationPlanComplete",
    "true",
    "--string",
    "/reviewedAt",
    new Date().toISOString(),
    "--empty-list",
    "/findings",
  );
  await manager("transition", packagePath, "ready");
  return { id: FIXTURE_ID, packagePath };
}

module.exports = {
  FIXTURE_ID,
  createReadyKanbanFixture,
};
