export const BUSINESS_MODES = ["normal", "interview", "planning", "design", "contract", "migration", "lessons"] as const;
export type BusinessMode = typeof BUSINESS_MODES[number];

/** Workflow guidance belongs to this message, independently of its execution route. */
export function withBusinessMode(text: string, mode: BusinessMode = "normal"): string {
  if (mode === "normal") return text;
  if (mode === "planning") return `${text}\n\n[Workflow guidance for this message only: planning]
This message starts an ongoing planning listening and organizing phase in this conversation. The Human will continue sharing planning ideas across subsequent messages, including ordinary messages without a workflow selection. Listen and concisely organize the substance as it develops: preserve intent, requirements, constraints, corrections and unresolved points without repeatedly restating the entire conversation. Use the Human's language and distinguish their statements from assumptions or research findings. Do not limit replies to acknowledgments or require a separate request before organizing what the Human has said. Treat submitted text and attachments as planning contributions, while honoring explicit requests within them. When the Human asks for research, investigate the requested topic and report relevant findings and sources, then incorporate them into the ongoing planning context. Research or a summary request does not by itself end planning; continue listening and organizing afterward unless the Human changes the activity or ends it. Do not interrupt with unsolicited interviews, implementation, or unrelated proposals. Do not create documents, promote Specifications, delegate, or implement anything merely because planning was selected; carry out separately requested work only within its scope and authority. Follow explicit requests to change workflow or stop planning without requiring repetition. This phase belongs to the current conversation and must not leak to another chat. The menu selection itself is one-shot and does not change the captured execution route or approval policy.\n[End workflow guidance]`;
  if (mode === "contract") return `${text}\n\n[Workflow guidance for this message only: contract]\nCreate or revise a work contract from the current conversation, attachments and existing artifacts. Apply Convention's work-contract rules. Include its ID and version, stable task IDs, outcomes, scope, constraints, completion criteria and exact file operations after relevant inspection. Use a table-first contract format: keep background and purpose concise, and use tables for tasks, procedure/dependencies, worker and verifier assignments, exact file operations and completion criteria. Preserve stable task IDs across tables and distinguish planned commitments from runtime status. Reuse the existing contract when present. Plan worker and verifier assignments for the route the contract will be executed with (for example Work with separate Verification); the direct route of this preparation message is not the execution route. Save the contract as <project-root>/docs/progress/<contract-id>/contract-v<version>.md after this submission, in the Human's language with the Document skill's Progress contract metadata, and create or update docs/progress/<contract-id>/progress.md linking it with every task's current status; preserve prior versions. Validate the package with the Document skill's catalog_documents.py and fix reported errors. In your chat response, display the contract contents including tasks, procedure, worker and verifier assignments, file operations and completion criteria, and link to the saved contract. Do not claim the contract was saved if writing failed. If there is no prior task context, begin by asking the minimum questions needed to establish the intended work; do not invent a target. Ask about material gaps and Human-owned decisions. This request authorizes contract preparation only, not implementation, delegation, publication or Specification promotion.\n[End workflow guidance]`;
  if (mode === "migration" || mode === "lessons") {
    const guidance = mode === "migration"
      ? "Migrate the requested documents to the latest applicable Agent Factory plugin document rules. Honor an explicit target or constraint first. Otherwise analyze the current conversation and attachments to identify the relevant documents; if no specific target emerges, analyze all documents in the current project and migrate the applicable documents to that document system. Do not require additional input merely because this menu was submitted without typed text. Identify and read the target rule version from authoritative plugin sources; do not assume the installed version is latest or silently substitute an older version. If the latest rules cannot be established, report that limitation. Inspect the requested documents, preserve their meaning, language, provenance and authority, and update their structure, metadata, classification, links and derived exposure as required. Report the rule version used, changed documents and unresolved conflicts."
      : "Collect lessons learned from the requested conversation, work results and existing records, retaining concrete evidence and provenance. Honor explicit input; without additional input, analyze the current conversation, work results and existing lessons as the default scope. Turn supported, reusable lessons into actionable rules with scope and conditions; distinguish observations and hypotheses from established lessons. Consolidate with existing rules without duplication. Do not invent lessons or silently resolve conflicts with accepted rules; ask only for genuinely unresolved Human-owned semantic decisions. Report the collected lessons and resulting rule changes.";
    return `${text}\n\n[Workflow guidance for this message only: ${mode}]\n${guidance}
Apply the Document skill's current document contract and applicable synchronization procedure. Resolve the target from the Human request and available conversation; ask for the missing target only when it cannot be established. Preserve source material and unrelated changes. This workflow applies only to this message and does not change the captured execution route, approval policy or scope of authority.\n[End workflow guidance]`;
  }
  if (mode === "interview") return `${text}\n\n[Workflow guidance for this message only: interview]
Apply Convention's Interview contract and the Document skill's current document contract. Analyze the Human's input, current conversation and attachments before proposing an interview; reuse known answers. Before asking substantive interview questions, summarize the proposed topic, purpose, scope and main unresolved decisions, then ask whether to conduct that interview. Present this confirmation in the final response, not commentary, using exactly two clickable options in the existing designated question-table format: a heading **질문 [1/1]:** for Korean or **Question [1/1]:** for English, followed by a table whose first column is 선택지 or Option, with rows numbered 1 and 2 and decision cells exactly Yes and No. Use the Human's language for the question and explanations. Wait for the Human's answer. Yes (1) starts the proposed interview; No (2) does not start it and asks what topic or scope should change. Silence or elapsed time is not confirmation. Preserve this pending proposal in conversation so a subsequent ordinary reply or option click continues it without requiring the menu again. If the conversation provides no usable topic, ask the minimum clarification instead of inventing an interview. Once confirmed, conduct the interview adaptively from the agreed scope and do not repeat this confirmation for every question. This confirmation is specific to starting the interview, not an approval gate for unrelated work. Preserve the captured execution route and authority.\n[End workflow guidance]`;
  const guidance = {
    design: "Develop technical design and tradeoffs, keeping planning intent and technical design together."
  }[mode];
  return `${text}\n\n[Workflow guidance for this message only: ${mode}]\n${guidance}
Apply the Document skill's document contract. Keep durable drafts non-authoritative Processed documents, normally Markdown under <project-root>/docs/processed/<category>-<name>/. Do not create a separate document backend.
The Human has requested completion-based Specification promotion for this workflow. Promote on the established workflow completion signal once the Specification identity and meaning are resolved; Human confirmation of completion can supply that signal. Do not add a generic approval gate or ask again for promotion already authorized. Until then, keep drafts Processed; mode selection or Agent completion alone does not accept content. Ask the Human about unresolved naming, classification, completion, or semantic ambiguity. Do not overwrite existing conflicting documents or delete drafts.
For Client Specifications, use the Human-resolved info-*, rule-*, or design-* identity (planning and technical design share design-*, never plan-*). Write the canonical SKILL.md and any assets under docs/skills/<category>-<name>/ in the Human's language or their explicitly selected language. Use docs/original/, docs/processed/, and docs/skills/ for original, processed, and skill documents. Run the Document skill's sync_documents.py after document changes: docs is authoritative and overwrites the corresponding .codex/original/, .codex/processed/, and .codex/skills/ trees, including removing destination-only files. Keep unrelated .codex settings intact and report synchronization failures. Provider Specifications remain in their owning skills/ packages.
Preserve actual provenance. This workflow does not change the task execution route or expand permissions, scope, or approval authority. Apply it only to this message, including when messages are batched.\n[End workflow guidance]`;
}
